# Alembic configuration file

[alembic]
# path to migration scripts
script_location = migrations

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
#file_template = %%(rev)s_%%(rev_timestamp)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# string value is passed to the `timestamp()` process using the `timezone` parameter
# Leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field of the filename (template)
# Set to 0 to omit slug entirely and rely on %(rev)s
# < -1 (negative) to only show the negative character count
# = -1 to indicate the absolute value of the length
# anything else 0 or > -1 represents an absolute length
# truncate_slug_len = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# logging configuration
# When set to 'false', the console output logging handler is disabled
# and logging configuration for the file handlers becomes independent.
# logging_config = file_logging.ini

# file to configure the logging module on the standard output
# as of SQLAlchemy 0.12, instead of --sql, --upgrade etc.
# you can use the below argument to supply extra logging config
# values to configure logging - here's where to supply log.excludes
# and log.level etc.
# logging_config =

[loggers]
keys = root,sqlalchemy.engine

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy.engine]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
